export const dummySupplierList: Array<any> = [
  {
    id: 1,
    supplierName: 'Wikibox',
    supplierContact: '648 789 0133',
    description: 'Respiratory abnorm NEC',
    itemName: 'Tomatoes',
  },
  {
    id: 2,
    supplierName: 'Nlounge',
    supplierContact: '201 367 5012',
    description: 'Screen mammogram NEC',
    itemName: 'Bread - Bagels, Mini',
  },
  {
    id: 3,
    supplierName: 'Fivespan',
    supplierContact: '761 844 1875',
    description: 'Complete edentulism NOS',
    itemName: 'Nacho Chips',
  },
  {
    id: 4,
    supplierName: 'Buzzbean',
    supplierContact: '877 655 5322',
    description: 'TB of organ NEC-unspec',
    itemName: 'Cheese - Marble',
  },
  {
    id: 5,
    supplierName: 'Quatz',
    supplierContact: '285 119 6231',
    description: 'TB of ureter-oth test',
    itemName: 'Pepper - Yellow Bell',
  },
  {
    id: 6,
    supplierName: 'Rhyloo',
    supplierContact: '505 411 4270',
    description: 'Cleft palate & lip NOS',
    itemName: 'Cookies - Englishbay Chochip',
  },
  {
    id: 7,
    supplierName: 'Gigabox',
    supplierContact: '244 730 2187',
    description: 'Primary CNS lymph multip',
    itemName: 'Nacho Chips',
  },
  {
    id: 8,
    supplierName: 'Cogilith',
    supplierContact: '422 862 3756',
    description: 'Lactation fail-postpart',
    itemName: 'Beets',
  },
  {
    id: 9,
    supplierName: 'Kwilith',
    supplierContact: '485 366 8193',
    description: 'Late effect CV dis NOS',
    itemName: 'Table Cloth 81x81 White',
  },
  {
    id: 10,
    supplierName: 'Babbleopia',
    supplierContact: '117 934 8486',
    description: 'Abn amnion NOS aff NB',
    itemName: 'Sparkling Wine - Rose, Freixenet',
  },
  {
    id: 11,
    supplierName: 'Mynte',
    supplierContact: '833 157 2595',
    description: 'Postcoital bleeding',
    itemName: 'Rambutan',
  },
  {
    id: 12,
    supplierName: 'Cogilith',
    supplierContact: '811 948 2398',
    description: 'Infestation NOS',
    itemName: 'Pasta - Cannelloni, Sheets, Fresh',
  },
  {
    id: 13,
    supplierName: 'Trupe',
    supplierContact: '300 295 1641',
    description: 'Nasal & sinus dis NEC',
    itemName: 'Turnip - White, Organic',
  },
  {
    id: 14,
    supplierName: 'Fiveclub',
    supplierContact: '148 330 6945',
    description: 'Dev disloc jt-lower leg',
    itemName: 'Wine - Vouvray Cuvee Domaine',
  },
  {
    id: 15,
    supplierName: 'Realbuzz',
    supplierContact: '937 528 6272',
    description: 'Externl cause status NEC',
    itemName: 'Potatoes - Yukon Gold, 80 Ct',
  },
  {
    id: 16,
    supplierName: 'Jabberstorm',
    supplierContact: '720 772 4244',
    description: 'Vomiting of fecal matter',
    itemName: 'Avocado',
  },
  {
    id: 17,
    supplierName: 'Babblestorm',
    supplierContact: '552 551 6104',
    description: 'Inj nerve pelv/leg NOS',
    itemName: 'Sproutsmustard Cress',
  },
  {
    id: 18,
    supplierName: 'Browsedrive',
    supplierContact: '899 958 4323',
    description: 'Acc poison-bromine cmpnd',
    itemName: 'Beef - Bones, Marrow',
  },
  {
    id: 19,
    supplierName: 'Jetwire',
    supplierContact: '128 713 4175',
    description: 'Abnormal feces',
    itemName: 'Veal - Tenderloin, Untrimmed',
  },
  {
    id: 20,
    supplierName: 'Janyx',
    supplierContact: '781 621 2252',
    description: 'Congen syph encephalitis',
    itemName: 'Rum - White, Gg White',
  },
];
